
version: '3.8'

services:
  n8n-collaboration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - WS_PORT=${WS_PORT:-3001}
      - HOST=${HOST:-0.0.0.0}
      - WS_HOST=${WS_HOST:-0.0.0.0}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - WS_PING_TIMEOUT=${WS_PING_TIMEOUT:-60000}
      - WS_PING_INTERVAL=${WS_PING_INTERVAL:-25000}
      - WS_MAX_HTTP_BUFFER_SIZE=${WS_MAX_HTTP_BUFFER_SIZE:-1000000}
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
        bind:
          create_host_path: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: n8n-collaboration-network
